### ISSUE TITLE
Please provide a copyright notice.

### ISSUE THREAD

**Issue by akazdayo** [lISIQI7/share-page#1]
Hello, IISIQI7

Thank you for creating a derivative app of PixelArt-Converter.
I think it is difficult to understand that the current state is a derivative application of PixelArt-Converter.
Please do the following
- Add descriptions in "README.md" and "share-page" that identify it as a derivative app of PixelArt-Converter created by akazdayo.
- Added changes from PixelArt-Converter in "README.md" and "share-page".
- Added copyright notice in "README.md", "share-page" and "LICENSE" (e.g. Modifications copyright (C) 2023 <your company/name>)

Thank you very much.

akaz

**Comment by lISIQI7** [comment]
Glad to receive your email😊, the result of the changes is here.
lISIQI7/share-page (github.com)




akaz's web page is really cool.Have a nice weekend,sir.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lISIQI7/share-page"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月12日(星期五) 下午5:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lISIQI7/share-page] Please provide a copyright notice. (Issue #1)





 
Hello, IISIQI7
 
Thank you for creating a derivative app of PixelArt-Converter.
 I think it is difficult to understand that the current state is a derivative application of PixelArt-Converter.
 Please do the following
  
Add descriptions in "README.md" and "share-page" that identify it as a derivative app of PixelArt-Converter created by akazdayo.
 
Added changes from PixelArt-Converter in "README.md" and "share-page".
 
Added copyright notice in "README.md", "share-page" and "LICENSE" (e.g. Modifications copyright (C) 2023 <your company/name&gt;)
  
Thank you very much.
 
akaz

**Comment by akazdayo** [comment]
Hi IISIQI7,
Thanks.

However, it seems that some fixes have not been completed.
Please fix them.

Thanks in Advance.

| Additional Contents | README.md | share-page | LICENSE |
| - | - | - | - |
| Please add a description in "README.md" and "share-page" indicating that this is a derivative application of PixelArt-Converter created by akazdayo. | completed | uncompleted |  |
| Please add changes from PixelArt-Converter to README.md and share-page. | uncompleted | uncompleted |  |
| Please add a copyright notice to "SHARE-PAGE" and "LICENSE". (e.g. Modifications copyright (C) 2023 <your company/name>). | completed | uncompleted | uncompleted |

akaz

**Comment by lISIQI7** [comment]
awesome,akaz's suggestions is so helpful. We can click on the link to view. ( https://share-page.streamlit.app/how_to_use )

And,the codding  is really fun. hope that this web-app can become  more and more fun. Such as build a playgroud and so on.

good luck,sincerely LISIQI7.😊

**Comment by akazdayo** [comment]
Hi lISIQI7,
Thanks for the correction 😊.

For the license, please copy and paste the Apache License 2.0 into your license with the following added at the end.

Modifications copyright (C) 2023 AKAZ and LISIQI7

Thanks in Advance.

**Comment by lISIQI7** [comment]
Okey,it has been finished.

 please   (https://github.com/lISIQI7/share-page/blob/main/LICENSE)

**Comment by akazdayo** [comment]
OK, Thanks for your quick action!

akaz

**Comment by lISIQI7** [comment]
the mean is  (All rights reserved) ? add it ?

**Comment by lISIQI7** [comment]
[Please provide a copyright notice.](https://github.com/lISIQI7/share-page/issues/1#top)🤔

**Comment by akazdayo** [comment]
yes please.

**Comment by lISIQI7** [comment]
Glad to see you.You know,You the notcice was added a few weeks ago.Maybe check it again, thanks👍


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lISIQI7/share-page"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月25日(星期四) 晚上8:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lISIQI7/share-page] Please provide a copyright notice. (Issue #1)





 
Reopened #1.

**Comment by lISIQI7** [comment]
It is done . (https://github.com/lISIQI7/share-page/blob/main/README.md)

**Comment by akazdayo** [comment]
Thank you so much😊
